# Generated by Django 3.2.15 on 2022-11-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_auto_20221121_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistcontent',
            name='content_type',
            field=models.CharField(choices=[('movie', 'movie'), ('tv_series', 'tv_series'), ('season', 'season'), ('episode', 'episode')], default='movie', max_length=50),
        ),
    ]
