# Generated by Django 3.2.15 on 2022-11-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_playlistcontent_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistcontent',
            name='content_type',
            field=models.CharField(choices=[('movie', 'movie'), ('episode', 'episode')], default='movie', max_length=50),
        ),
    ]
