# Generated by Django 3.2.15 on 2022-11-21 05:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0004_alter_playlistcontent_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistcontent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='playlistcontent',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
