# Generated by Django 3.2.15 on 2022-11-21 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0005_auto_20221121_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistcontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='playlistcontent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
