# Generated by Django 3.2.15 on 2022-11-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0006_auto_20221121_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistcontent',
            name='season',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='playlistcontent',
            name='series',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
