# Generated by Django 3.2.15 on 2022-11-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0007_auto_20221121_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistcontent',
            name='episode_num',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
