# Generated by Django 3.2.15 on 2022-11-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0008_playlistcontent_episode_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistcontent',
            name='episode_num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='playlistcontent',
            name='season',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='playlistcontent',
            name='series',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
